config/routes.rb
Rails.application.routes.draw do
  # post 'tasks' => 'tasks#create'

  resources :categories do
    resource :tasks, only: %i[new, create destroy] # route new не появляеться
  end

  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
require_relative '../../utils/glue'

class Category < Glue::ApplicationRecord
  has_one :task
  has_and_belongs_to_many :products, dependent: :destroy

  validates :name, presence: true
  validates :url, format: { with: /https:\/\/cars.av.by/ }
end

# Есть зацикленность. Если в базе нету категории, на сайте она не отрисуеться. Если она не отрисуеться - ее не обновить

app/models/product.rb
require_relative '../../utils/glue'

class Product < Glue::ApplicationRecord
  has_and_belongs_to_many :categories, touch: :categories_updated_at # check, delete .save in parser!

  validates :ad_id, numericality: { only_integer: true }
  validates :name, presence: true
  validates :url, format: { with: /https:\/\/cars.av.by/ }
  validates :price, numericality: {only_integer: true, greater_than: 0}
  #validates :price, { numericality: {only_integer: true} }
end

# add indexing for ad_id.
# Не нравиться переделанные [PHOTOS]. Теперь там 1на photo_url!

app/models/task.rb
require_relative '../../utils/glue'

class Task < Glue::ApplicationRecord
  belongs_to :category

  validates :recursive, inclusion: { in: [true, false] }
  validates :skip_products, inclusion: { in: [true, false] }
  validates :url_type, format: { with: /category|products/ }
  # add validates for state, if that need
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    # @default = ActionController::Base.helpers.asset_path('../assets/images/default_auto.jpeg')
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :url)
  end

end

# По нажатию кнопки update_category сделать задание в таблице Tasks

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index; end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new # не появляется в routes
    @category = Category.find(params[:category_id])
  end

  def create
    @category = Category.find(params[:category_id])

    render categories_path if params[:category_id] == '1' # для теста update all. Чтоне не обновлять реально.

    # connection 'one to one'. I catch an error when i do build_task because @task.id is exist
    return if @category.task # render('wrong')

    @task = @category.build_task({ skip_products: false, recursive: true, state: 'pending', url_type: 'category' })
    @task.save ? redirect_to(category_path(@category)) : render('wrong')
  end

  def destroy
    # Временно для обнуления tasks вручную. id = 0
    if params[:category_id] == '0'
      Task.delete_all
    else
      @category = Category.find(params[:category_id])
      @task.destroy
    end

    redirect_to(categories_path)
  end

  private

  def task_params
    # params.require(:task).permit(:title, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_category.erb
<li class='category'>

    <% if @category.name == 'All' %>
      <span class="category__name"><%= @category.name %></span>
    <% else %>
      <%= link_to "#{@category.name}", category_path(@category), class: 'category__name' %>
    <% end %>

  <span class="category__count"><%= @category.products.size %></span>
</li>

app/views/categories/_dropdown.erb
<%= collection_select(:product, :category_id, @categories, :id, :name, prompt: 'категории') %>

<!-- select("post", "category_id", @categories.collect {|r| [ r.name, r.id ] }, { include_blank: 'категории' }) -->

app/views/categories/_update_button.erb
<% unless @category.task || (@category.updated_at > Time.now - 3.hours) %>
  <span class='category__update'>
    <%= link_to 'update', category_tasks_path(@category), method: :post %>
  </span>
<% end %>

app/views/categories/index.html.erb
<header><h1>Categories</h1></header>

<div class="menu">
  <div class="menu__item"><%= link_to 'New category', new_category_path %></div>
  <div class="menu__item"><%= button_to "Clear Tasks", category_tasks_path({category_id: 0}), method: :delete %></div>
</div>

<ul class='categories'>
  <% @categories.each do |category| %>

    <%= render @category = category %>

  <% end %>
</ul>

app/views/categories/new.erb
<h1>NEW</h1>

<p><%= @category.inspect %></p>

<%= form_with scope: :category , url: categories_path, local: true do |form| %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :url %><br>
    <%= form.text_area :url %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.erb
<div class="category_products">
  <%=  link_to '⇐', categories_path,  class: 'link_back' %>

  <p class="category">
    <span class="category__name"><%= @category.name %></span>
    <span class="category__count"><%= @category.products.size %></span>
    <span class='category__update_info'>(last update: <%= @category.updated_at.getlocal.strftime('%H:%M   %d.%m.%Y') %>)</span>
    <%= render 'update_button' %>
  </p>

  <ul class="products">
    <%= render @category.products %>
  </ul>
</div>

<%=  link_to '⇐', categories_path,  class: 'link_back' %>
<!--# last update == Time.new but in the site time == time - 3 hours !-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Av</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_product.erb
<li class='product'>

  <img
    class='product__image'
    alt='image car'
    src=<%= product.photo_url ? product.photo_url : '' %> />

  <ul class='product__info'>
    <li class='product__info_ad_id'><span>ad_id</span>  <%= product.ad_id %></li>
    <li class='product__info_url'><span>more information:</span><a href=' <%= product.url %>'>link</a></li>
    <li class='product__info_name'><span>model:</span>  <%= product.name %> </li>
    <li class='product__info_year'><span>year:</span>  <%= product.year %> </li>
    <li class='product__info_price'><span>price:</span>  <%= product.price %>$</li>
    <li class='product__info_city'><span>city:</span>  <%= product.city %> </li>
    <% description = product.description && product.description.size > 40 ? product.description[1..40]+'...' : product.description %>
    <li class='product__info_description'><span>description:</span> <%= description %></li>
  </ul>
</li>

app/views/products/index.html.erb
<h3>Products#index</h3>

app/views/tasks/new.erb
<h3>Create new task</h3>

<%= form_with model: [@category, @category.task.build], local: true do |form| %>
  <p>
    <%= form.label :url_type %><br>
    <%= form.text_field :url_type %>
  </p>
  <p><%= form.check_box :recursive %></p>
  <p><%= form.check_box :skip_products %></p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', categories_path %>

app/views/tasks/wrong.erb
<h1>Something went wrong</h1>